version: '3'

services:
  jupyter:
    image: jupyter/datascience-notebook
    restart: unless-stopped
    ports:
      - 8888:8888
    environment:
      NB_UID: 1000
      NB_GID: 100
    links:
      - clickhouse
    volumes:
      - ./jupyter-data-dir:/home/jovyan/work
    # for password using generate pwd hash IPython.lib.passwd()
    # command: start-notebook.sh --NotebookApp.password='sha1:{Generate with IPython.lib.passwd()}'

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    restart: unless-stopped
    links:
      - clickhouse
    ports:
      - 8080:80
    # environment:
    #   USER: user
    #   PASSWORD: password

  clickhouse:
    build: ./clickhouse
    restart: unless-stopped
    ports:
      - 8123:8123 # for http clients
      - 9000:9000 # for console client
    volumes:
      # Store data to HDD
      - ./clickhouse-data:/var/lib/clickhouse/
      # Base Clickhouse cfg
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
